apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-app
  namespace: my-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: my-app 
    spec:
      containers:
        - image: index.docker.io/linux17kartik/node-mysql:v17
          name: node-mysql-container
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: my-app-port


