apiVersion: v1
kind: Service
metadata:
  name: sqlproxyservice
  namespace: db
  labels:
    app: cloudsqlproxy
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: cloudsqlproxy
